### ISSUE TITLE
As a tournament director, I want to be able to do CRUD operations on tournaments.

### ISSUE THREAD

**Issue by FrozenSync** [VU-Distributed-Bridge/Firepanel#7]
### Goal
The tournament director should be able to create, read, update and delete tournaments.

### Requirements
Tournament data should be displayed in a sortable data table which supports CRUD operations. Tournament data should consist of the following properties:
- name
- date

**Comment by ThiloKielmann** [comment]
been thinking quite a while about this. the result is simple:  a tournment should be identifief with a name and a date.

**Comment by FrozenSync** [comment]
Hmm, what about assigning Raspberry Pis to a tournament? Should it be part of the tournament setup process or separate?

**Comment by ThiloKielmann** [comment]
just added a list of todo's on the project panel, among which answering this question. Is this what you were looking for?

**Comment by FrozenSync** [comment]
Incorporated the following note into this issue:
```
have a list of tournaments, add and delete them, and delete the related firestore data on deletion of the tournament
```
Updated the issue to reflect the final specs.
